import { describe, expect, it } from "vitest";
import {
  createCircuitContext,
  createConstructorContext,
  type CircuitContext,
} from "@midnight-ntwrk/compact-runtime";
import {
  Contract,
  Phase,
  ledger,
  pureCircuits,
  type Witnesses,
} from "../contract/managed/voting/contract/index.js";
import { witnesses, type PrivateState } from "../src/contract/witnesses";
import { encodeProposal as proposalId, toHex } from "../src/lib/bytes";

// These tests execute the circuits generated by compactc 0.31.1 through the
// Compact runtime. Every rejection below is an `assert` inside the circuit, so
// a modified client cannot bypass it: the same assertion is part of the proof.

const bytes = (n: number) => new Uint8Array(32).fill(n);
const organizer = bytes(1);
const election = bytes(2);
const alice = bytes(10);
const bob = bytes(11);
const mallory = bytes(66);
const P1 = proposalId("budget-2026");
const P2 = proposalId("new-logo");
const coinKey = "00".repeat(32);
const address = "01".repeat(32);

function setup(custom: Witnesses<PrivateState> = witnesses) {
  const contract = new Contract(custom);
  const initial = contract.initialState(
    createConstructorContext({ organizerSecret: organizer }, coinKey),
    election,
    pureCircuits.organizerCommitment(organizer),
  );
  let context: CircuitContext<PrivateState> = createCircuitContext(
    address,
    coinKey,
    initial.currentContractState,
    { organizerSecret: organizer },
  );
  const as = (ps: PrivateState) => {
    context = { ...context, currentPrivateState: ps };
  };
  const run = <R extends { context: CircuitContext<PrivateState> }>(
    fn: (c: CircuitContext<PrivateState>) => R,
  ): R => {
    const out = fn(context);
    context = out.context;
    return out;
  };
  const c = contract.impureCircuits;
  return {
    get state() {
      return ledger(context.currentQueryContext.state);
    },
    as,
    register: (secret: Uint8Array) =>
      run((ctx) =>
        c.registerVoter(ctx, pureCircuits.voterCommitment(election, secret)),
      ),
    closeRegistration: () => run((ctx) => c.closeRegistration(ctx)),
    open: (p: Uint8Array) => run((ctx) => c.openProposal(ctx, p)),
    close: () => run((ctx) => c.closeProposal(ctx)),
    vote: (secret: Uint8Array, p: Uint8Array, yes: boolean) => {
      as({ voterSecret: secret });
      try {
        return run((ctx) => c.castVote(ctx, p, yes));
      } finally {
        as({ organizerSecret: organizer });
      }
    },
  };
}

function readyElection(custom?: Witnesses<PrivateState>) {
  const app = setup(custom);
  app.register(alice);
  app.register(bob);
  app.closeRegistration();
  app.open(P1);
  return app;
}

const tally = (app: ReturnType<typeof setup>, p: Uint8Array) => [
  app.state.yesVotes.lookup(p).read(),
  app.state.noVotes.lookup(p).read(),
];

describe("successful election", () => {
  it("counts one vote from each registered voter and returns the proposal-scoped nullifier", () => {
    const app = readyElection();
    const result = app.vote(alice, P1, true);
    app.vote(bob, P1, false);
    expect(result.result).toEqual(
      pureCircuits.voteNullifier(election, P1, alice),
    );
    expect(tally(app, P1)).toEqual([1n, 1n]);
    expect(app.state.nullifiers.size()).toBe(2n);
  });

  it("lets the same voter vote once on each proposal with unlinkable nullifiers", () => {
    const app = readyElection();
    const first = app.vote(alice, P1, true).result;
    app.close();
    app.open(P2);
    const second = app.vote(alice, P2, false).result;
    expect(first).not.toEqual(second);
    expect(tally(app, P1)).toEqual([1n, 0n]);
    expect(tally(app, P2)).toEqual([0n, 1n]);
  });
});

describe("double voting", () => {
  it("rejects a second vote by the same voter on the same proposal", () => {
    const app = readyElection();
    app.vote(alice, P1, true);
    expect(() => app.vote(alice, P1, false)).toThrow(
      "Already voted on this proposal",
    );
    expect(tally(app, P1)).toEqual([1n, 0n]);
  });

  it("rejects re-voting on a proposal after it was closed and a new one opened", () => {
    const app = readyElection();
    app.vote(alice, P1, true);
    app.close();
    expect(() => app.open(P1)).toThrow("Proposal was already used");
    app.open(P2);
    expect(() => app.vote(alice, P1, true)).toThrow("Proposal is not active");
  });

  it("rejects duplicate voter registration", () => {
    const app = setup();
    app.register(alice);
    expect(() => app.register(alice)).toThrow("Voter already registered");
    expect(app.state.registered.size()).toBe(1n);
  });
});

describe("unauthorized participation", () => {
  it("rejects a voter who is not on the electoral roll", () => {
    const app = readyElection();
    // The honest witness finds no path; the circuit-level checks are exercised
    // by the malicious-witness tests below.
    expect(() => app.vote(mallory, P1, true)).toThrow("not registered");
    expect(tally(app, P1)).toEqual([0n, 0n]);
  });

  it("rejects a malicious witness that reuses another voter's valid path", () => {
    const app = readyElection({
      ...witnesses,
      membershipPath: ({ ledger, privateState }) => [
        privateState,
        ledger.voters.findPathForLeaf(
          pureCircuits.voterCommitment(election, alice),
        )!,
      ],
    });
    expect(() => app.vote(mallory, P1, true)).toThrow(
      "Membership path does not match voter",
    );
  });

  it("rejects a forged Merkle path whose leaf matches but whose siblings do not", () => {
    const app = readyElection({
      ...witnesses,
      membershipPath: (ctx, leaf) => {
        const path = ctx.ledger.voters.findPathForLeaf(leaf)!;
        return [
          ctx.privateState,
          {
            ...path,
            path: path.path.map((p, i) =>
              i === 0 ? { ...p, sibling: { field: p.sibling.field + 1n } } : p,
            ),
          },
        ];
      },
    });
    expect(() => app.vote(alice, P1, true)).toThrow(
      "Voter is not on the electoral roll",
    );
  });

  it("rejects organizer actions from anyone without the organizer secret", () => {
    const app = setup();
    app.as({ organizerSecret: mallory });
    expect(() => app.register(alice)).toThrow("Organizer authorization required");
    expect(() => app.closeRegistration()).toThrow(
      "Organizer authorization required",
    );
    const ready = readyElection();
    ready.as({ organizerSecret: mallory });
    expect(() => ready.close()).toThrow("Organizer authorization required");
  });

  it("does not let a registered voter act as organizer", () => {
    const app = setup();
    app.as({ organizerSecret: alice });
    expect(() => app.register(mallory)).toThrow(
      "Organizer authorization required",
    );
  });
});

describe("lifecycle transitions", () => {
  it("starts in registration and rejects voting or opening proposals there", () => {
    const app = setup();
    app.register(alice);
    expect(app.state.phase).toBe(Phase.registration);
    expect(() => app.open(P1)).toThrow("Close voter registration");
    expect(() => app.vote(alice, P1, true)).toThrow("No proposal is active");
  });

  it("refuses to seal an empty roll and to seal twice", () => {
    const app = setup();
    expect(() => app.closeRegistration()).toThrow(
      "Register at least one voter first",
    );
    app.register(alice);
    app.closeRegistration();
    expect(app.state.phase).toBe(Phase.idle);
    expect(() => app.closeRegistration()).toThrow("already closed");
    expect(() => app.register(bob)).toThrow("Voter registration is closed");
  });

  it("allows only one active proposal at a time", () => {
    const app = readyElection();
    expect(app.state.phase).toBe(Phase.voting);
    expect(() => app.open(P2)).toThrow("Another proposal is already active");
  });

  it("rejects votes naming a proposal other than the active one", () => {
    const app = readyElection();
    expect(() => app.vote(alice, P2, true)).toThrow("Proposal is not active");
  });

  it("rejects votes and closing when no proposal is active", () => {
    const app = readyElection();
    app.close();
    expect(app.state.phase).toBe(Phase.idle);
    expect(() => app.vote(alice, P1, true)).toThrow("No proposal is active");
    expect(() => app.close()).toThrow("No proposal is active");
  });
});

describe("privacy boundary", () => {
  it("keeps the voter secret and roll entry out of the public transcript", () => {
    const app = readyElection();
    const result = app.vote(alice, P1, true);
    const transcript = JSON.stringify(
      result.proofData.publicTranscript,
      (_, v) =>
        v instanceof Uint8Array
          ? toHex(v)
          : typeof v === "bigint"
            ? v.toString()
            : v,
    );
    expect(transcript).toContain(toHex(result.result));
    expect(transcript).not.toContain(toHex(alice));
    expect(transcript).not.toContain(
      toHex(pureCircuits.voterCommitment(election, alice)),
    );
  });

  it("domain-separates commitments, nullifiers, elections and proposals", () => {
    const leaf = pureCircuits.voterCommitment(election, alice);
    const nul = pureCircuits.voteNullifier(election, P1, alice);
    expect(leaf).not.toEqual(nul);
    expect(nul).not.toEqual(pureCircuits.voteNullifier(bytes(3), P1, alice));
    expect(nul).not.toEqual(pureCircuits.voteNullifier(election, P2, alice));
    expect(leaf).not.toEqual(pureCircuits.voterCommitment(bytes(3), alice));
  });
});
