// Deploys the voting contract to a Midnight test network (Preview by default) with a real wallet, runs one
// full election against it and records every finalized transaction in
// deployments/<network>.json. Nothing in that file is generated locally: each
// txId and block height comes from the indexer after finalization, and
// `npm run verify:preview` re-checks all of it against the public indexer.
//
// Usage:
//   docker compose up -d                  # pinned proof server on 127.0.0.1:6300
//   MIDNIGHT_SEED=<64 hex chars> npm run deploy:preview
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  deployContract,
  findDeployedContract,
} from "@midnight-ntwrk/midnight-js-contracts";
import { httpClientProofProvider } from "@midnight-ntwrk/midnight-js-http-client-proof-provider";
import { indexerPublicDataProvider } from "@midnight-ntwrk/midnight-js-indexer-public-data-provider";
import { levelPrivateStateProvider } from "@midnight-ntwrk/midnight-js-level-private-state-provider";
import { NodeZkConfigProvider } from "@midnight-ntwrk/midnight-js-node-zk-config-provider";
import type { FinalizedTxData } from "@midnight-ntwrk/midnight-js-types";
import { pureCircuits } from "../contract/managed/voting/contract/index.js";
import { networkConfig, paths, toolchain } from "./config";
import {
  compiledContract,
  type VotingCircuit,
  type VotingProviders,
} from "./contract";
import { buildWallet, waitUntilFunded, walletProvider } from "./wallet";
import { fromHex, proposalId, randomSecret, toHex } from "./bytes";
import {
  evidencePath,
  verifierKeyHashes,
  type Evidence,
  type RecordedTx,
} from "./evidence";
import type { PrivateState } from "../src/contract/witnesses";

const log = (line: string) => console.log(`  ${line}`);
const PROPOSAL = "Adopt the 2027 club budget?";

async function loadSecrets(network: string) {
  const file = path.join(paths.secrets, `${network}.json`);
  try {
    const raw = JSON.parse(await readFile(file, "utf8"));
    return {
      organizer: fromHex(raw.organizer),
      election: fromHex(raw.election),
      voters: (raw.voters as string[]).map((v) => fromHex(v)),
    };
  } catch {
    const fresh = {
      organizer: randomSecret(),
      election: randomSecret(),
      voters: [randomSecret(), randomSecret(), randomSecret()],
    };
    await mkdir(paths.secrets, { recursive: true });
    await writeFile(
      file,
      JSON.stringify(
        {
          organizer: toHex(fresh.organizer),
          election: toHex(fresh.election),
          voters: fresh.voters.map(toHex),
        },
        null,
        2,
      ),
      { mode: 0o600 },
    );
    log(`Generated private election secrets in ${file} (git-ignored).`);
    return fresh;
  }
}

async function main() {
  const seed = process.env.MIDNIGHT_SEED;
  if (!seed || !/^[0-9a-f]{64}$/i.test(seed))
    throw new Error(
      "Set MIDNIGHT_SEED to a 32-byte hex wallet seed funded on the target network.",
    );
  const config = networkConfig();
  console.log(`NightVote deployment → ${config.name}`);
  log(`Proof server: ${config.proofServer}`);

  const wallet = await buildWallet(config, seed);
  log(`Fund this wallet if needed: ${config.faucet}`);
  await waitUntilFunded(wallet, log);
  const walletAndMidnight = await walletProvider(wallet);
  const zkConfigProvider = new NodeZkConfigProvider<VotingCircuit>(
    paths.zkConfig,
  );
  const accountId = walletAndMidnight.getCoinPublicKey();
  const providers: VotingProviders = {
    privateStateProvider: levelPrivateStateProvider({
      privateStateStoreName: `nightvote-${config.name}`,
      accountId,
      privateStoragePasswordProvider: () =>
        `${Buffer.from(accountId, "hex").toString("base64")}!`,
    }),
    publicDataProvider: indexerPublicDataProvider(
      config.indexer,
      config.indexerWS,
    ),
    zkConfigProvider,
    proofProvider: httpClientProofProvider(config.proofServer, zkConfigProvider),
    walletProvider: walletAndMidnight,
    midnightProvider: walletAndMidnight,
  };

  const secrets = await loadSecrets(config.name);
  const proposal = proposalId(PROPOSAL);
  const transactions: RecordedTx[] = [];
  const rejectedLocally: Evidence["rejectedLocally"] = [];
  const record = (step: string, circuit: string, tx: FinalizedTxData) => {
    if (tx.status !== "SucceedEntirely")
      throw new Error(`${step} finalized with status ${tx.status}.`);
    transactions.push({
      step,
      circuit,
      txId: tx.txId,
      txHash: tx.txHash,
      blockHeight: tx.blockHeight,
      status: tx.status,
    });
    log(`✓ ${step} — tx ${tx.txId} in block ${tx.blockHeight}`);
  };

  log("Deploying contract (proof generated by the local proof server)…");
  const deployed = await deployContract(providers, {
    compiledContract,
    privateStateId: "organizer",
    initialPrivateState: { organizerSecret: secrets.organizer },
    args: [secrets.election, pureCircuits.organizerCommitment(secrets.organizer)],
  });
  const contractAddress = deployed.deployTxData.public.contractAddress;
  record("deploy", "constructor", deployed.deployTxData.public);

  const join = (id: string, state: PrivateState) =>
    findDeployedContract(providers, {
      compiledContract,
      contractAddress,
      privateStateId: id,
      initialPrivateState: state,
    });

  for (const [i, voter] of secrets.voters.entries())
    record(
      `register voter ${i + 1}`,
      "registerVoter",
      (
        await deployed.callTx.registerVoter(
          pureCircuits.voterCommitment(secrets.election, voter),
        )
      ).public,
    );
  record(
    "seal electoral roll",
    "closeRegistration",
    (await deployed.callTx.closeRegistration()).public,
  );
  record(
    `open proposal "${PROPOSAL}"`,
    "openProposal",
    (await deployed.callTx.openProposal(proposal)).public,
  );

  const ballots = [true, false, true];
  for (const [i, voter] of secrets.voters.entries()) {
    const asVoter = await join(`voter-${i + 1}`, { voterSecret: voter });
    record(
      `voter ${i + 1} votes ${ballots[i] ? "yes" : "no"}`,
      "castVote",
      (await asVoter.callTx.castVote(proposal, ballots[i])).public,
    );
  }

  // The second ballot fails inside the circuit before any proof exists, so no
  // transaction can be produced. Record the reason for the evidence file.
  try {
    const again = await join("voter-1", { voterSecret: secrets.voters[0] });
    await again.callTx.castVote(proposal, false);
    throw new Error("Double vote was accepted — refusing to record evidence.");
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    if (!/Already voted on this proposal/.test(reason)) throw error;
    rejectedLocally.push({ step: "voter 1 votes again", reason });
    log("✓ voter 1 second ballot rejected by the circuit");
  }

  record(
    "close proposal",
    "closeProposal",
    (await deployed.callTx.closeProposal()).public,
  );

  const evidence: Evidence = {
    schema: "nightvote-deployment/v1",
    network: config.name,
    contractAddress,
    electionId: toHex(secrets.election),
    organizerCommitment: toHex(
      pureCircuits.organizerCommitment(secrets.organizer),
    ),
    deployedAt: new Date().toISOString(),
    toolchain,
    verifierKeySha256: await verifierKeyHashes(),
    proposal: { label: PROPOSAL, id: toHex(proposal) },
    transactions,
    rejectedLocally,
    expected: {
      registeredVoters: secrets.voters.length,
      yes: ballots.filter(Boolean).length,
      no: ballots.filter((b) => !b).length,
      nullifiers: secrets.voters.length,
    },
  };
  await mkdir(paths.deployments, { recursive: true });
  await writeFile(
    evidencePath(config.name),
    `${JSON.stringify(evidence, null, 2)}\n`,
  );
  console.log(`\nContract address: ${contractAddress}`);
  console.log(`Evidence written to ${evidencePath(config.name)}`);
  console.log(`Verify independently: npm run verify:preview`);
  await wallet.wallet.stop();
}

main().then(
  () => process.exit(0),
  (error) => {
    console.error(`\nDeployment failed: ${error instanceof Error ? error.message : error}`);
    process.exit(1);
  },
);
